import { AppShell } from "../components/layout/AppShell";
import { BadgePill } from "../components/shared/BadgePill";
import { useHealth } from "../queries/useHealth";

const AGENT_MODE_EXPLAINER: Record<string, string> = {
  mock: "Deterministic, offline compliance checks — no LLM calls, no API key required.",
  openai: "Findings and chat are generated by an OpenAI model (see backend/.env).",
  vertex: "Findings and chat are generated by Vertex AI Gemini (GCP-hosted).",
};

const COMING_SOON_SETTINGS = [
  "Team accounts & SSO",
  "Firm system integrations (SharePoint, ACC, Procore)",
  "Sketch export / DXF write-back",
  "Semantic & graph knowledge store (OpenSearch / Neo4j)",
];

export function Settings() {
  const { data: health, isLoading, isError } = useHealth();

  return (
    <AppShell>
      <div className="mx-auto max-w-2xl px-6 py-10">
        <h1 className="text-xl font-semibold text-ink-primary">Settings</h1>
        <p className="mt-1 text-sm text-ink-secondary">
          This is a single-user demo workspace — no accounts, no sign-in.
        </p>

        <div className="mt-6 rounded-lg border border-line bg-navy-900 p-5">
          <div className="flex items-center justify-between">
            <p className="text-sm font-medium text-ink-primary">Agent mode</p>
            <BadgePill tone="built" />
          </div>
          {isLoading && <p className="mt-2 text-xs text-ink-muted">Checking…</p>}
          {isError && <p className="mt-2 text-xs text-danger">Backend unreachable.</p>}
          {health && (
            <>
              <p className="mt-2 font-mono text-sm text-accent">{health.agent_mode}</p>
              <p className="mt-2 text-xs leading-relaxed text-ink-secondary">
                {AGENT_MODE_EXPLAINER[health.agent_mode] ?? ""}
              </p>
            </>
          )}
        </div>

        <h2 className="mt-8 text-sm font-medium uppercase tracking-wider text-ink-muted">
          Coming soon
        </h2>
        <div className="mt-3 space-y-2">
          {COMING_SOON_SETTINGS.map((item) => (
            <div
              key={item}
              className="flex items-center justify-between rounded-lg border border-line bg-navy-900 px-4 py-3"
            >
              <span className="text-sm text-ink-secondary">{item}</span>
              <BadgePill tone="coming-soon" />
            </div>
          ))}
        </div>
      </div>
    </AppShell>
  );
}
